In [3]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

# https://www.datacamp.com/tutorial/pandas-read-csv

colNames = {
    "Year": "year",
    "Company name": "company_name",
    "Reporting on a Mandatory Basis": "report_mandatory",
    " Number of single use plastic bags issued ": "bags_issued",
    " Gross proceeds of charge (£) ": "gross_proceeds",
    "VAT (£)": "vat",
    "Costs deducted (£)": "costs_deducted",
    " Cost of changing till systems (£)": "cost_till_systems",
    "Cost of staff communications (£)": "cost_staff_comms",
    "Cost of customer communications (£)": "cost_customer_comms",
    "...": "...",
    " Net proceeds  (£) (Gross less VAT and costs) ": "net_proceeds",
    "Use of net proceeds": "net_proceeds_use",
    "Other use of net proceeds": "net_proceeds_use_other",
    "Amount donated to good causes (£)": "amount_donated",
    "Good causes in receipt of proceed donation": "good_causes",
    "Number of paper bags issued": "num_paper_bags_issued",
    "Number of bags for life issued": "num_bags_for_life_issued",
    "Number of fabric bags issued": "num_fabric_bags_issued",
    "Number of other bags issued": "num_other_bags_issued",
    "Any other information": "notes",
}
# usecols=usecols
df = pd.read_csv('./data.csv', encoding='cp1252', thousands=',')
#df.head()

In [7]:
# filter to one year
sdf = df
#sdf = df[df["Year"] == "2016-17"]

# select specific columns
bagsColumn = " Number of single use plastic bags issued "
sdf = sdf[["Year", "Company name", bagsColumn]]

# Get the top ten values per year
sdf = sdf.sort_values(by=["Year", bagsColumn], ascending=[True, False])
sdf = sdf.groupby('Year', as_index=False).nth[:10]

sdf = sdf.insert(2, [1,2,3,4,5,6,7,8,9,10], True)

sdf.reset_index()

sdf.head()

,Year,Company name,Number of single use plastic bags issued
211,2016-17,Tesco Stores Ltd,637181382
256,2016-17,Wm Morrison Supermarkets PLC,191508650
7,2016-17,Asda Stores Limited,165766608
159,2016-17,Ocado Retail Limited,128388732
215,2016-17,The Co-operative Group,125929333

In [81]:
filename = './subdata.json'

# sdf.to_csv(filename, sep='\t', encoding='utf-8', index=False)

sdf.to_json(filename, orient='records')

In [ ]:

sdf = sdf.head(10)
sdf.head()


xAxis = sdf["Year"]
bagCount = sdf[["Company name", bagsColumn]]


x = np.arange(len(xAxis))  # the label locations

width = 0.10  # the width of the bars
multiplier = 0
fig, ax = plt.subplots(layout='constrained')

for attribute, measurement in bagCount.items():
    offset = width * multiplier
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1


# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_ylabel('Length (mm)')
ax.set_title('Charty')
ax.set_xticks(x + width, xAxis)
ax.legend(loc='upper left', ncols=3)
ax.set_ylim(0, 250)

plt.show()